# Generated by Django 2.0.9 on 2019-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0039_auto_20190105_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='camp_type',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='campaign_size',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='is_skip',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='stor_location',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='multiple_campaign_upload',
            name='campaign_uploaded_by',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='multiple_campaign_upload',
            unique_together={('campaign_uploaded_by', 'campaign_name')},
        ),
    ]
