version: '3'

services:
  web:
    build: .
    command: gunicorn signagecms.wsgi --bind 0.0.0.0:8001 --workers 3
    ports:
      - "8001:8001"
    volumes:
       - .:/src
    networks:
      - backend
  
  nginx:
    image: nginx:latest

    ports:
       - "8080:80"
    volumes:
       - .:/src
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       
    networks:
       - backend
    depends_on:
       - web
  
networks:
  backend:
    driver: bridge