# Generated by Django 2.0.9 on 2019-02-20 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20190220_1427'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmsapp', '0042_multiple_campaign_upload_save_path'),
        ('campaign', '0002_deleted_campaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_Group_Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 2, 20, 14, 27, 29, 387662))),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Multiple_campaign_upload')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GcGroups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 14, 27, 29, 386663)),
        ),
    ]
