# Generated by Django 2.0.9 on 2019-03-21 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20190321_1525'),
        ('cmsapp', '0042_multiple_campaign_upload_save_path'),
        ('campaign', '0027_auto_20190319_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('times_played', models.SmallIntegerField(default=1)),
                ('duration', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 25, 6, 935099))),
                ('campaign', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Multiple_campaign_upload')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='approved_group_campaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 25, 6, 934100)),
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 25, 6, 933100)),
        ),
        migrations.AlterField(
            model_name='player_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 25, 6, 934100)),
        ),
    ]
