# Generated by Django 2.0.9 on 2019-03-21 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_auto_20190321_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign_reports',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaign_reports',
            name='player',
        ),
        migrations.AlterField(
            model_name='approved_group_campaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 55, 32, 3493)),
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 55, 32, 495)),
        ),
        migrations.AlterField(
            model_name='player_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 15, 55, 32, 6497)),
        ),
        migrations.DeleteModel(
            name='Campaign_Reports',
        ),
    ]
