# Generated by Django 2.2 on 2019-05-07 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0042_merge_20190507_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_campaign',
            name='schedule_type',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='approved_group_campaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 12, 41, 46, 466731)),
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 12, 41, 46, 466731)),
        ),
        migrations.AlterField(
            model_name='player_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 12, 41, 46, 467730)),
        ),
        migrations.CreateModel(
            name='Schedule_Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_from', models.DateTimeField()),
                ('schedule_to', models.DateTimeField()),
                ('player_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Player_Campaign')),
            ],
        ),
        migrations.AddIndex(
            model_name='schedule_campaign',
            index=models.Index(fields=['schedule_from', 'schedule_to'], name='campaign_sc_schedul_91c536_idx'),
        ),
    ]
