# Generated by Django 2.0.9 on 2019-05-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0042_merge_20190506_1428'),
        ('campaign', '0043_auto_20190507_1241'),
    ]

    operations = [
    ]
