# Generated by Django 2.2 on 2019-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0043_auto_20190507_1241'),
        ('campaign', '0042_merge_20190506_1428'),
    ]

    operations = [
    ]
