# Generated by Django 2.0.9 on 2019-05-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0045_auto_20190511_1755'),
        ('campaign', '0044_merge_20190508_1646'),
    ]

    operations = [
    ]
