# Generated by Django 2.2 on 2019-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0044_merge_20190510_1142'),
        ('campaign', '0046_merge_20190515_1611'),
    ]

    operations = [
    ]
