# Generated by Django 2.1.5 on 2019-05-24 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0046_merge_20190515_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_campaign',
            name='pc_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule_campaign',
            name='sc_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approved_group_campaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 10, 57, 32, 178499)),
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 10, 57, 32, 178499)),
        ),
        migrations.AlterField(
            model_name='player_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 10, 57, 32, 194504)),
        ),
    ]
