# Generated by Django 2.2 on 2019-05-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0047_auto_20190524_1057'),
        ('campaign', '0047_merge_20190517_1512'),
    ]

    operations = [
    ]
