# Generated by Django 2.1.5 on 2019-05-29 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0047_auto_20190524_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_campaign',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='approved_group_campaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 11, 34, 2, 630822)),
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 11, 34, 2, 630822)),
        ),
        migrations.AlterField(
            model_name='player_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 11, 34, 2, 654822)),
        ),
    ]
