# Generated by Django 2.2 on 2019-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0048_auto_20190529_1134'),
        ('campaign', '0048_merge_20190528_1018'),
    ]

    operations = [
    ]
