# Generated by Django 2.2 on 2019-06-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0049_auto_20190607_1221'),
        ('campaign', '0050_auto_20190530_1431'),
    ]

    operations = [
    ]
