# Generated by Django 2.1.5 on 2019-08-02 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0012_auto_20190802_1219'),
        ('campaign', '0059_auto_20190802_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_campaign',
            name='device_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device_group.Device_Group'),
        ),
        migrations.AlterField(
            model_name='approved_group_campaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 19, 54, 589501)),
        ),
        migrations.AlterField(
            model_name='deleted_campaigns',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 19, 54, 563502)),
        ),
        migrations.AlterField(
            model_name='player_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 12, 19, 54, 591499)),
        ),
    ]
