# Generated by Django 2.2 on 2019-08-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0063_auto_20190805_1758'),
        ('campaign', '0063_auto_20190805_1515'),
    ]

    operations = [
    ]
