# Generated by Django 2.0.9 on 2019-05-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0002_auto_20190423_1120'),
        ('device_group', '0002_auto_20190425_1125'),
    ]

    operations = [
    ]
