# Generated by Django 2.2 on 2019-05-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0003_merge_20190506_1428'),
        ('device_group', '0003_merge_20190507_1238'),
    ]

    operations = [
    ]
