# Generated by Django 2.0.9 on 2019-05-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0003_merge_20190507_1238'),
        ('device_group', '0003_merge_20190506_1428'),
    ]

    operations = [
    ]
