# Generated by Django 2.0.9 on 2019-05-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0004_merge_20190508_1646'),
        ('device_group', '0004_merge_20190511_1752'),
    ]

    operations = [
    ]
