# Generated by Django 2.2 on 2019-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0004_merge_20190510_1142'),
        ('device_group', '0005_merge_20190515_1611'),
    ]

    operations = [
    ]
