# Generated by Django 2.2 on 2019-05-30 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0006_merge_20190517_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_group_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 14, 31, 50, 524971)),
        ),
    ]
