# Generated by Django 2.1.5 on 2019-08-02 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0012_auto_20190802_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_group_campaign',
            name='dgc_is_skip',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device_group_campaign',
            name='dgc_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device_group_campaign',
            name='dgc_schedule_type',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='device_group_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 14, 20, 27, 201978)),
        ),
    ]
