# Generated by Django 2.1.5 on 2019-08-05 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0013_auto_20190802_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_group_campaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 17, 58, 56, 519361)),
        ),
    ]
