# Generated by Django 2.0.9 on 2019-02-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0040_auto_20190201_1030'),
        ('group', '0002_auto_20190213_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCampaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Multiple_campaign_upload')),
                ('gc_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GcGroups')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupcampaigns',
            unique_together={('gc_group', 'campaign')},
        ),
    ]
