# Generated by Django 2.0.9 on 2019-02-16 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20190213_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
