# Generated by Django 2.0.9 on 2019-02-16 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190216_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcgroupmembers',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 17, 15, 39, 199100)),
        ),
    ]
