# Generated by Django 2.0.9 on 2019-02-18 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20190216_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 12, 13, 2, 520952)),
        ),
    ]
