# Generated by Django 2.0.9 on 2019-02-18 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20190218_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 14, 58, 53, 666987)),
        ),
    ]
