# Generated by Django 2.0.9 on 2019-02-20 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20190218_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 14, 27, 29, 390660)),
        ),
    ]
