# Generated by Django 2.0.9 on 2019-03-01 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_auto_20190220_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberAssignNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('creator_name', models.CharField(max_length=20)),
                ('member', models.TextField()),
                ('gc_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GcGroups')),
            ],
        ),
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 18, 53, 20, 170340)),
        ),
    ]
