# Generated by Django 2.0.9 on 2019-03-01 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20190301_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberassignnotification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 19, 6, 47, 721318)),
        ),
    ]
