# Generated by Django 2.0.9 on 2019-03-01 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_auto_20190301_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmemberassignnotification',
            name='creator_name',
        ),
        migrations.RemoveField(
            model_name='groupmemberassignnotification',
            name='g_name',
        ),
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 19, 11, 8, 544615)),
        ),
    ]
