# Generated by Django 2.0.9 on 2019-03-02 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_auto_20190301_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 17, 14, 57, 656208)),
        ),
    ]
