# Generated by Django 2.0.9 on 2019-03-05 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_auto_20190302_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCampaignAssignNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.TextField()),
                ('message', models.TextField()),
                ('gc_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GcGroups')),
            ],
        ),
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 11, 54, 28, 810363)),
        ),
    ]
