# Generated by Django 2.0.9 on 2019-03-07 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_auto_20190307_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 13, 1, 7, 595145)),
        ),
    ]
