# Generated by Django 2.0.9 on 2019-03-07 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20190307_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 13, 3, 38, 751267)),
        ),
    ]
