# Generated by Django 2.0.9 on 2019-03-08 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_auto_20190308_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 17, 55, 18, 554583)),
        ),
    ]
