# Generated by Django 2.0.9 on 2019-03-08 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_auto_20190308_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 17, 58, 8, 847742)),
        ),
    ]
