# Generated by Django 2.0.13 on 2019-03-13 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_auto_20190308_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 12, 11, 18, 809528)),
        ),
    ]
