# Generated by Django 2.0.9 on 2019-03-16 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0027_auto_20190313_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 0, 31, 113061)),
        ),
    ]
