# Generated by Django 2.0.9 on 2019-03-16 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0030_auto_20190316_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 15, 21, 37, 202553)),
        ),
    ]
