# Generated by Django 2.0.9 on 2019-03-19 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0031_auto_20190316_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 11, 7, 4, 515382)),
        ),
    ]
