# Generated by Django 2.2 on 2019-04-25 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0045_auto_20190328_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 11, 25, 19, 998719)),
        ),
    ]
