# Generated by Django 2.2 on 2019-05-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0046_auto_20190423_1120'),
        ('group', '0046_auto_20190425_1125'),
    ]

    operations = [
    ]
