# Generated by Django 2.0.9 on 2019-05-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0047_merge_20190507_1238'),
        ('group', '0047_merge_20190506_1428'),
    ]

    operations = [
    ]
