# Generated by Django 2.2 on 2019-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0047_merge_20190506_1428'),
        ('group', '0047_merge_20190507_1238'),
    ]

    operations = [
    ]
