# Generated by Django 2.1.5 on 2019-08-16 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0042_auto_20190816_1431'),
        ('group', '0055_auto_20190816_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='G_Player',
        ),
        migrations.AlterField(
            model_name='groupcampaigns',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 14, 31, 26, 455641)),
        ),
    ]
