# Generated by Django 2.0.9 on 2019-03-07 07:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('status', models.SmallIntegerField(default=0)),
                ('fcm_id', models.CharField(max_length=125)),
                ('expiry_date', models.DateTimeField()),
                ('registered_at', models.DateTimeField(default=datetime.datetime(2019, 3, 7, 13, 1, 7, 600140))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'mac')},
        ),
    ]
