# Generated by Django 2.0.9 on 2019-03-07 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activated_by',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 13, 3, 38, 754265)),
        ),
    ]
