# Generated by Django 2.0.9 on 2019-03-08 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20190307_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mac',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 17, 48, 48, 145616)),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
