# Generated by Django 2.0.9 on 2019-03-12 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20190308_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Geder_Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 43, 42, 37015))),
                ('g_male', models.IntegerField(default=0)),
                ('g_female', models.IntegerField(default=0)),
                ('age_0_2', models.IntegerField(default=0)),
                ('age_4_6', models.IntegerField(default=0)),
                ('age_8_12', models.IntegerField(default=0)),
                ('age_15_20', models.IntegerField(default=0)),
                ('age_25_32', models.IntegerField(default=0)),
                ('age_38_43', models.IntegerField(default=0)),
                ('age_48_53', models.IntegerField(default=0)),
                ('age_60_100', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 43, 42, 37015)),
        ),
        migrations.AddField(
            model_name='age_geder_metrics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
