# Generated by Django 2.0.9 on 2019-03-16 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20190313_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_Sync_Metrics',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.Player')),
                ('accessed_at', models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 0, 31, 118820))),
            ],
        ),
        migrations.AlterField(
            model_name='age_geder_metrics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 0, 31, 118820)),
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 0, 31, 118820)),
        ),
    ]
