# Generated by Django 2.0.9 on 2019-03-16 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20190316_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age_geder_metrics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 14, 38, 14, 77302)),
        ),
        migrations.AlterField(
            model_name='auto_sync_metrics',
            name='accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 14, 38, 14, 81303)),
        ),
        migrations.AlterField(
            model_name='player',
            name='fcm_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 14, 38, 14, 77302)),
        ),
    ]
