# Generated by Django 2.0.9 on 2019-03-16 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20190316_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Seen_Metrics',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.Player')),
                ('accessed_at', models.DateTimeField(default=datetime.datetime(2019, 3, 16, 15, 21, 37, 210531))),
            ],
        ),
        migrations.RemoveField(
            model_name='auto_sync_metrics',
            name='player',
        ),
        migrations.AlterField(
            model_name='age_geder_metrics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 15, 21, 37, 210531)),
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 15, 21, 37, 210531)),
        ),
        migrations.DeleteModel(
            name='Auto_Sync_Metrics',
        ),
    ]
