# Generated by Django 2.0.9 on 2019-03-22 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_auto_20190321_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age_geder_metrics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 25, 59, 151952)),
        ),
        migrations.AlterField(
            model_name='campaign_reports',
            name='campaign',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign_reports',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 25, 59, 155951)),
        ),
        migrations.AlterField(
            model_name='last_seen_metrics',
            name='accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 25, 59, 151952)),
        ),
        migrations.AlterField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 25, 59, 151952)),
        ),
    ]
