# Generated by Django 2.0.9 on 2019-05-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0031_auto_20190423_1120'),
        ('player', '0031_auto_20190425_1125'),
    ]

    operations = [
    ]
