# Generated by Django 2.2 on 2019-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0032_merge_20190506_1427'),
        ('player', '0032_merge_20190507_1238'),
    ]

    operations = [
    ]
