# Generated by Django 2.0.9 on 2019-05-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0032_merge_20190507_1238'),
        ('player', '0032_merge_20190506_1427'),
    ]

    operations = [
    ]
