# Generated by Django 2.0.9 on 2019-05-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0033_merge_20190508_1646'),
        ('player', '0033_merge_20190511_1751'),
    ]

    operations = [
    ]
