# Generated by Django 2.2 on 2019-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0034_merge_20190515_1611'),
        ('player', '0033_merge_20190510_1142'),
    ]

    operations = [
    ]
