# Generated by Django 2.2 on 2019-06-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0036_auto_20190530_1431'),
        ('player', '0036_auto_20190603_1220'),
    ]

    operations = [
    ]
