# Generated by Django 2.2 on 2019-08-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0043_auto_20190816_1439'),
        ('player', '0041_auto_20190805_1515'),
    ]

    operations = [
    ]
