# Generated by Django 2.2 on 2019-09-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0044_merge_20190820_1107'),
        ('player', '0044_auto_20190828_1122'),
    ]

    operations = [
    ]
