# Generated by Django 2.1.5 on 2019-05-31 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot_device', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOT_Deivce',
            new_name='IOT_Device',
        ),
    ]
