# Generated by Django 2.1.5 on 2019-06-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0002_auto_20190531_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_device',
            name='key',
            field=models.CharField(db_index=True, default='adskite', max_length=125, unique=True),
        ),
    ]
