# Generated by Django 2.1.5 on 2019-06-01 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0042_multiple_campaign_upload_save_path'),
        ('iot_device', '0004_auto_20190601_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAR_Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Multiple_campaign_upload')),
            ],
        ),
        migrations.CreateModel(
            name='Contextual_Ads_Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(db_index=True, max_length=125)),
                ('delay_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.IOT_Device')),
            ],
        ),
        migrations.AddField(
            model_name='car_campaign',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.Contextual_Ads_Rule'),
        ),
    ]
