# Generated by Django 2.1.5 on 2019-06-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0036_auto_20190603_1220'),
        ('cmsapp', '0042_multiple_campaign_upload_save_path'),
        ('iot_device', '0006_car_device'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car_campaign',
            unique_together={('car', 'campaign')},
        ),
        migrations.AlterUniqueTogether(
            name='car_device',
            unique_together={('car', 'player')},
        ),
    ]
