# Generated by Django 2.1.5 on 2019-06-05 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0007_auto_20190603_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Geder_Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('g_male', models.IntegerField(default=0)),
                ('g_female', models.IntegerField(default=0)),
                ('age_0_2', models.IntegerField(default=0)),
                ('age_4_6', models.IntegerField(default=0)),
                ('age_8_12', models.IntegerField(default=0)),
                ('age_15_20', models.IntegerField(default=0)),
                ('age_25_32', models.IntegerField(default=0)),
                ('age_38_43', models.IntegerField(default=0)),
                ('age_48_53', models.IntegerField(default=0)),
                ('age_60_100', models.IntegerField(default=0)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.IOT_Device')),
            ],
        ),
    ]
