# Generated by Django 2.1.5 on 2019-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0008_age_geder_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='mac',
            field=models.CharField(db_index=True, max_length=125),
        ),
        migrations.AlterUniqueTogether(
            name='iot_device',
            unique_together={('mac', 'device_type')},
        ),
    ]
