# Generated by Django 2.1.5 on 2019-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0009_auto_20190624_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextual_ads_rule',
            name='accessed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
