# Generated by Django 2.1.5 on 2019-07-09 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0010_contextual_ads_rule_accessed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geder_Age_Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('f_age_0_2', models.IntegerField(default=0)),
                ('f_age_4_6', models.IntegerField(default=0)),
                ('f_age_8_12', models.IntegerField(default=0)),
                ('f_age_15_20', models.IntegerField(default=0)),
                ('f_age_25_32', models.IntegerField(default=0)),
                ('f_age_38_43', models.IntegerField(default=0)),
                ('f_age_48_53', models.IntegerField(default=0)),
                ('f_age_60_100', models.IntegerField(default=0)),
                ('m_age_0_2', models.IntegerField(default=0)),
                ('m_age_4_6', models.IntegerField(default=0)),
                ('m_age_8_12', models.IntegerField(default=0)),
                ('m_age_15_20', models.IntegerField(default=0)),
                ('m_age_25_32', models.IntegerField(default=0)),
                ('m_age_38_43', models.IntegerField(default=0)),
                ('m_age_48_53', models.IntegerField(default=0)),
                ('m_age_60_100', models.IntegerField(default=0)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.IOT_Device')),
            ],
        ),
    ]
