# Generated by Django 2.1.5 on 2019-07-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0011_geder_age_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_CAR_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('classifier_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.Contextual_Ads_Rule', unique=True)),
            ],
        ),
    ]
