# Generated by Django 2.1.5 on 2019-07-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0012_gps_car_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_car_data',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iot_device.Contextual_Ads_Rule'),
        ),
    ]
