# Generated by Django 2.0.9 on 2019-03-28 09:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPwdSession',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('session_key', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 3, 28, 14, 30, 22, 369923))),
            ],
        ),
    ]
