# Generated by Django 2.2 on 2019-05-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20190507_1238'),
        ('accounts', '0004_merge_20190506_1428'),
    ]

    operations = [
    ]
