# Generated by Django 2.0.9 on 2019-05-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20190511_1751'),
        ('accounts', '0005_merge_20190508_1645'),
    ]

    operations = [
    ]
