# Generated by Django 2.2 on 2019-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20190515_1611'),
        ('accounts', '0005_merge_20190510_1142'),
    ]

    operations = [
    ]
