# Generated by Django 2.1.5 on 2019-09-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_name',
            field=models.CharField(default='', max_length=125),
        ),
    ]
