# Generated by Django 2.1.5 on 2019-09-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(default='image', max_length=15),
        ),
    ]
