# Generated by Django 2.1.5 on 2019-10-01 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_approved',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 15, 6, 21, 647847)),
        ),
    ]
