# Generated by Django 2.0.9 on 2019-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License_Device',
            fields=[
                ('mac', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=1)),
                ('expiry_date', models.DateTimeField()),
                ('registered_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
