# Generated by Django 2.1.5 on 2019-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_device',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='license_device',
            name='org_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
